// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contact_me: dynamic(() => import("./ContactMe")),
  content_index: dynamic(() => import("./ContentIndex")),
  content_index_cert: dynamic(() => import("./ContentIndexCert")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  integrations: dynamic(() => import("./Integrations")),
  link_block: dynamic(() => import("./LinkBlock")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
